name: Terraform Dynatrace CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write   
  contents: read

env:
  TF_VAR_dt_env_url: ${{ secrets.DT_ENV_URL }}
  TF_VAR_dt_api_token: ${{ secrets.DT_API_TOKEN }}
  TF_VAR_oauth_client_id: ${{ secrets.OAUTH_CLIENT_ID }}
  TF_VAR_oauth_client_secret: ${{ secrets.OAUTH_CLIENT_SECRET }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: dynatrace-prod

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2 
      
      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::058264264614:role/GitHubActionsTerraformState
          role-session-name: gha-terraform
          aws-region: us-east-1

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Format Check
      - name: Terraform Format
        run: terraform fmt -check

      # Step 6: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 7: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false -no-color 
            
      # Step 8: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
